/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mydomain.myproject;

import java.net.HttpURLConnection;
import java.awt.Image;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileSystemView;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author nathan
 */
public class HttpUrlReaderGUI extends javax.swing.JFrame {

    /**
     * Creates new form HttpUrlReaderGUI
     */
    File iconFile;
    public HttpUrlReaderGUI() {
        initComponents();
        iconFile = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel3 = new javax.swing.JPanel();
        imgLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        sendButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        urlField = new javax.swing.JTextField();
        statusLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        imgLabel.setBackground(new java.awt.Color(0, 0, 0));
        imgLabel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                imgLabelComponentResized(evt);
            }
        });
        jPanel3.add(imgLabel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 260;
        gridBagConstraints.ipady = 200;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        getContentPane().add(jPanel3, gridBagConstraints);

        jPanel4.setPreferredSize(new java.awt.Dimension(420, 187));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jButton1.setText("Cancel");
        jPanel2.add(jButton1, java.awt.BorderLayout.WEST);

        sendButton.setText("Send");
        sendButton.setMinimumSize(new java.awt.Dimension(80, 31));
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });
        jPanel2.add(sendButton, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(70, 0, 0, 0);
        jPanel4.add(jPanel2, gridBagConstraints);

        jPanel1.setPreferredSize(new java.awt.Dimension(260, 37));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("URL:");
        jPanel1.add(jLabel2, java.awt.BorderLayout.WEST);

        urlField.setPreferredSize(new java.awt.Dimension(220, 27));
        jPanel1.add(urlField, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 263;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.weightx = 0.1;
        jPanel4.add(jPanel1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(50, 0, 0, 0);
        jPanel4.add(statusLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        getContentPane().add(jPanel4, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setIconFile(String filepath) {
        iconFile = new File(filepath);
    }
    
    private void setIcon() {
        ImageIcon icon = new ImageIcon(iconFile.getPath());
        int width = icon.getIconWidth();
        int height = icon.getIconHeight();
        float ratio = (float)imgLabel.getHeight() / icon.getIconHeight();
        Image image = icon.getImage().getScaledInstance(Math.round(width * ratio), Math.round(height * ratio), Image.SCALE_FAST);
        icon.setImage(image);
        imgLabel.setHorizontalAlignment(JLabel.CENTER);
        imgLabel.setIcon(icon);
    }
    
    private void setStatus(int code, String filename) {
        switch (code) 
        {
            case HttpURLConnection.HTTP_OK:
                statusLabel.setText("Successfully downloaded: " + filename);
            break;
            case HttpURLConnection.HTTP_ACCEPTED:
                statusLabel.setText("Successfully downloaded: " + filename);
            break;
            case HttpURLConnection.HTTP_BAD_REQUEST:
                statusLabel.setText("");
            break;
            case HttpURLConnection.HTTP_UNAUTHORIZED:
                statusLabel.setText("");
            break;
            case HttpURLConnection.HTTP_PAYMENT_REQUIRED:
                statusLabel.setText("");
            break;
            case HttpURLConnection.HTTP_FORBIDDEN:
                statusLabel.setText("");
            break;
            case HttpURLConnection.HTTP_NOT_FOUND:
                statusLabel.setText("");
            break;
        }
    }
    
    private void imgLabelComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_imgLabelComponentResized
        // TODO add your handling code here:
        if (iconFile != null)
            setIcon();
    }//GEN-LAST:event_imgLabelComponentResized

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        if (urlField.getText().isEmpty())
            return;
        HttpUrlReader http = new HttpUrlReader();
        try {
            String filePath = "";
            JFileChooser save = new JFileChooser(FileSystemView.getFileSystemView().getHomeDirectory());
            save.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
            save.setFileFilter(new FileNameExtensionFilter("Image Files", "png", "gif", "jpg"));

            int returnValue = save.showSaveDialog(null);
            if (returnValue == JFileChooser.APPROVE_OPTION) {
                if (save.getSelectedFile().isDirectory()) {
                    filePath = save.getSelectedFile().getPath();
                    String filename = urlField.getText().substring(
                        urlField.getText().lastIndexOf("/"));
                    filePath = filePath + filename;
                } else {
                    filePath = save.getSelectedFile().getPath();
                }
                int response = http.sendGet(urlField.getText(), filePath);
                setStatus(response, filePath);
                setIconFile(filePath);
                setIcon();
            }

        } catch (Exception ex) {
            Logger.getLogger(HttpUrlReaderGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sendButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HttpUrlReaderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HttpUrlReaderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HttpUrlReaderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HttpUrlReaderGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HttpUrlReaderGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton sendButton;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField urlField;
    // End of variables declaration//GEN-END:variables
}
